Imports System.Reflection

Namespace oData

    ''' <summary>
    '''
    ''' This code was generated by the Schema Utility.
    '''
    ''' Form: ZODA_LOAD as List(Of rowZODA_LOAD)
    ''' Date: 26/05/2020
    '''
    ''' </summary>
    <oFormClass("rowZODA_LOAD")>
    Public Class ZODA_LOAD : Inherits oForm

        ''' <summary>
        ''' ZODA_LOAD Constructor method.
        ''' </summary>
        ''' <param name="Sender">The Assembly.GetExecutingAssembly of your project</param>
        ''' <param name="Parent">Optional: Parent oRow of this form</param>
        Sub New(ByRef Sender As Assembly, Optional Parent As oRow = Nothing)
            MyBase.New(Sender, Parent)

        End Sub

        ''' <summary>
        ''' Add a new row to the ZODA_LOAD form.
        ''' </summary>
        ''' <returns>rowZODA_LOAD</returns>
        Public Function AddRow() As rowZODA_LOAD
            With Me
                .Add(New rowZODA_LOAD(Me))
                Return .Last

            End With

        End Function

    End Class

    ''' <summary>
    ''' Defines rows in the ZODA_LOAD form.
    ''' </summary>
    <oRowClass("ZODA_LOAD", "serialZODA_LOAD")>
    Public Class rowZODA_LOAD : Inherits oRow

        ''' <summary>
        ''' rowZODA_LOAD Constructor method.
        ''' </summary>
        ''' <param name="Parent">Parent oForm of this row</param>
        Sub New(Parent As oForm)
            MyBase.New(Parent)

        End Sub

        ''' <summary>
        ''' Get / Set the "Record Type" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("Record Type", mandatory:=True, length:=3)>
        Public Property RECORDTYPE As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "Loaded?" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("Loaded?", length:=1)>
        Public Property LOADED As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "Key 1" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("Key 1", length:=20)>
        Public Property KEY1 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "Key 2" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("Key 2", length:=20)>
        Public Property KEY2 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "Key 3" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("Key 3", length:=20)>
        Public Property KEY3 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT1" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT1", length:=30)>
        Public Property TEXT1 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT2" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT2", length:=30)>
        Public Property TEXT2 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT3" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT3", length:=30)>
        Public Property TEXT3 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT4" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT4", length:=30)>
        Public Property TEXT4 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT5" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT5", length:=30)>
        Public Property TEXT5 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT6" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT6", length:=30)>
        Public Property TEXT6 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT7" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT7", length:=30)>
        Public Property TEXT7 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT8" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT8", length:=30)>
        Public Property TEXT8 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT9" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT9", length:=30)>
        Public Property TEXT9 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT10" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT10", length:=30)>
        Public Property TEXT10 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT11" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT11", length:=50)>
        Public Property TEXT11 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT12" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT12", length:=50)>
        Public Property TEXT12 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT13" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT13", length:=50)>
        Public Property TEXT13 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT14" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT14", length:=50)>
        Public Property TEXT14 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT15" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT15", length:=50)>
        Public Property TEXT15 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT16" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT16", length:=50)>
        Public Property TEXT16 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT17" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT17", length:=50)>
        Public Property TEXT17 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT18" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT18", length:=50)>
        Public Property TEXT18 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT19" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT19", length:=50)>
        Public Property TEXT19 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT20" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT20", length:=50)>
        Public Property TEXT20 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT21" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT21", length:=100)>
        Public Property TEXT21 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT22" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT22", length:=100)>
        Public Property TEXT22 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT23" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT23", length:=100)>
        Public Property TEXT23 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT24" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT24", length:=100)>
        Public Property TEXT24 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT25" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT25", length:=100)>
        Public Property TEXT25 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT26" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT26", length:=100)>
        Public Property TEXT26 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT27" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT27", length:=100)>
        Public Property TEXT27 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT28" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT28", length:=100)>
        Public Property TEXT28 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT29" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT29", length:=100)>
        Public Property TEXT29 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "TEXT30" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>String</returns>	
        <oDataColumn("TEXT30", length:=100)>
        Public Property TEXT30 As String
            Get
                Return getProperty()
            End Get
            Set(value As String)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "INT1" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>Integer</returns>	
        <oDataColumn("INT1")>
        Public Property INT1 As Integer
            Get
                Return getProperty()
            End Get
            Set(value As Integer)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "INT2" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>Integer</returns>	
        <oDataColumn("INT2")>
        Public Property INT2 As Integer
            Get
                Return getProperty()
            End Get
            Set(value As Integer)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "INT3" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>Integer</returns>	
        <oDataColumn("INT3")>
        Public Property INT3 As Integer
            Get
                Return getProperty()
            End Get
            Set(value As Integer)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "INT4" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>Integer</returns>	
        <oDataColumn("INT4")>
        Public Property INT4 As Integer
            Get
                Return getProperty()
            End Get
            Set(value As Integer)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "INT5" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>Integer</returns>	
        <oDataColumn("INT5")>
        Public Property INT5 As Integer
            Get
                Return getProperty()
            End Get
            Set(value As Integer)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "INT6" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>Integer</returns>	
        <oDataColumn("INT6")>
        Public Property INT6 As Integer
            Get
                Return getProperty()
            End Get
            Set(value As Integer)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "INT7" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>Integer</returns>	
        <oDataColumn("INT7")>
        Public Property INT7 As Integer
            Get
                Return getProperty()
            End Get
            Set(value As Integer)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "INT8" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>Integer</returns>	
        <oDataColumn("INT8")>
        Public Property INT8 As Integer
            Get
                Return getProperty()
            End Get
            Set(value As Integer)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "INT9" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>Integer</returns>	
        <oDataColumn("INT9")>
        Public Property INT9 As Integer
            Get
                Return getProperty()
            End Get
            Set(value As Integer)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "INT10" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>Integer</returns>	
        <oDataColumn("INT10")>
        Public Property INT10 As Integer
            Get
                Return getProperty()
            End Get
            Set(value As Integer)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "REAL1" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>Decimal</returns>	
        <oDataColumn("REAL1")>
        Public Property REAL1 As Decimal
            Get
                Return getProperty()
            End Get
            Set(value As Decimal)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "REAL2" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>Decimal</returns>	
        <oDataColumn("REAL2")>
        Public Property REAL2 As Decimal
            Get
                Return getProperty()
            End Get
            Set(value As Decimal)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "REAL3" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>Decimal</returns>	
        <oDataColumn("REAL3")>
        Public Property REAL3 As Decimal
            Get
                Return getProperty()
            End Get
            Set(value As Decimal)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "REAL4" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>Decimal</returns>	
        <oDataColumn("REAL4")>
        Public Property REAL4 As Decimal
            Get
                Return getProperty()
            End Get
            Set(value As Decimal)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "REAL5" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>Decimal</returns>	
        <oDataColumn("REAL5")>
        Public Property REAL5 As Decimal
            Get
                Return getProperty()
            End Get
            Set(value As Decimal)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "REAL6" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>Decimal</returns>	
        <oDataColumn("REAL6")>
        Public Property REAL6 As Decimal
            Get
                Return getProperty()
            End Get
            Set(value As Decimal)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "REAL7" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>Decimal</returns>	
        <oDataColumn("REAL7")>
        Public Property REAL7 As Decimal
            Get
                Return getProperty()
            End Get
            Set(value As Decimal)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "REAL8" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>Decimal</returns>	
        <oDataColumn("REAL8")>
        Public Property REAL8 As Decimal
            Get
                Return getProperty()
            End Get
            Set(value As Decimal)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "REAL9" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>Decimal</returns>	
        <oDataColumn("REAL9")>
        Public Property REAL9 As Decimal
            Get
                Return getProperty()
            End Get
            Set(value As Decimal)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "REAL10" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>Decimal</returns>	
        <oDataColumn("REAL10")>
        Public Property REAL10 As Decimal
            Get
                Return getProperty()
            End Get
            Set(value As Decimal)
                setProperty(value)
            End Set
        End Property

        ''' <summary>
        ''' Get / Set the "Ln" Value of ZODA_LOAD.
        ''' </summary>
        ''' <returns>Integer</returns>	
        <oDataColumn("Ln", Key:=True)>
        Public Property LINE As Integer
            Get
                Return getProperty()
            End Get
            Set(value As Integer)
                setProperty(value)
            End Set
        End Property


    End Class

    ''' <summary>
    ''' A nullable version of rowZODA_LOAD.
    '''
    ''' This is used to deserialise JSON data
    ''' and should not be instantiated directly.
    ''' </summary>
    Public Class serialZODA_LOAD

        Public Property RECORDTYPE As String
        Public Property LOADED As String
        Public Property KEY1 As String
        Public Property KEY2 As String
        Public Property KEY3 As String
        Public Property TEXT1 As String
        Public Property TEXT2 As String
        Public Property TEXT3 As String
        Public Property TEXT4 As String
        Public Property TEXT5 As String
        Public Property TEXT6 As String
        Public Property TEXT7 As String
        Public Property TEXT8 As String
        Public Property TEXT9 As String
        Public Property TEXT10 As String
        Public Property TEXT11 As String
        Public Property TEXT12 As String
        Public Property TEXT13 As String
        Public Property TEXT14 As String
        Public Property TEXT15 As String
        Public Property TEXT16 As String
        Public Property TEXT17 As String
        Public Property TEXT18 As String
        Public Property TEXT19 As String
        Public Property TEXT20 As String
        Public Property TEXT21 As String
        Public Property TEXT22 As String
        Public Property TEXT23 As String
        Public Property TEXT24 As String
        Public Property TEXT25 As String
        Public Property TEXT26 As String
        Public Property TEXT27 As String
        Public Property TEXT28 As String
        Public Property TEXT29 As String
        Public Property TEXT30 As String
        Public Property INT1 As Integer?
        Public Property INT2 As Integer?
        Public Property INT3 As Integer?
        Public Property INT4 As Integer?
        Public Property INT5 As Integer?
        Public Property INT6 As Integer?
        Public Property INT7 As Integer?
        Public Property INT8 As Integer?
        Public Property INT9 As Integer?
        Public Property INT10 As Integer?
        Public Property REAL1 As Decimal?
        Public Property REAL2 As Decimal?
        Public Property REAL3 As Decimal?
        Public Property REAL4 As Decimal?
        Public Property REAL5 As Decimal?
        Public Property REAL6 As Decimal?
        Public Property REAL7 As Decimal?
        Public Property REAL8 As Decimal?
        Public Property REAL9 As Decimal?
        Public Property REAL10 As Decimal?
        Public Property LINE As Integer?


    End Class

End Namespace