Public Class mandates : Implements IDisposable

    Private _id As String
    ''' <summary> 
    '''This is the bank account ID returned by Paysafe that can be used later to look up or update a mandate.
    ''' </summary> 
    ''' <returns></returns> 
    Public Property id As String
        Get
            Return _id
        End Get
        Set(value As String)
            _id = value
        End Set
    End Property

    Private _reference As String
    ''' <summary> 
    '''This is the identifier of the mandate in the banking system. SEPA allowed characters are A-Z0-9 (),-./?. 
    '''BACS allowed characters are A-Z0-9 .&/- and the reference must begin with A-Z or 0-9.
    ''' </summary> 
    ''' <returns></returns> 
    Public Property reference As String
        Get
            Return _reference
        End Get
        Set(value As String)
            _reference = value
        End Set
    End Property

    Private _bankAccountId As String
    ''' <summary> 
    '''This is the bank account that this mandate belongs to.
    ''' </summary> 
    ''' <returns></returns> 
    Public Property bankAccountId As String
        Get
            Return _bankAccountId
        End Get
        Set(value As String)
            _bankAccountId = value
        End Set
    End Property

    Private _status As String
    ''' <summary> 
    '''This is the mandate status. Possible values are:
    '''INITIAL – The mandate has been created but is not ready to be batched
    '''PENDING – The mandate is ready to be batched
    '''DECLINED – The mandate was not accepted for batching
    '''BATCHED – The mandate has been batched (sent into the bacs system)
    '''ACTIVE – The mandate has been batch for more than 5 business days and no returns have been received that would invalidate it
    '''CANCELLED – The mandate has been cancelled
    '''REJECTED – A return has been received that prevents the mandate from being used in a transaction
    '''DISPUTED – A return has been received that disputes the mandates validity
    '''INACTIVE – The mandate has been deleted
    ''' </summary> 
    ''' <returns></returns> 
    Public Property status As String
        Get
            Return _status
        End Get
        Set(value As String)
            _status = value
        End Set
    End Property

    Private _paymentToken As String
    ''' <summary> 
    '''This is a token generated by Paysafe that represents the mandate and is returned in the response to the mandate creation request. 
    '''It can be used for payments in our payment APIs.
    ''' </summary> 
    ''' <returns></returns> 
    Public Property paymentToken As String
        Get
            Return _paymentToken
        End Get
        Set(value As String)
            _paymentToken = value
        End Set
    End Property

    Private _statusChangeDate As String
    ''' <summary> 
    '''The date that the status was last changed
    ''' </summary> 
    ''' <returns></returns> 
    Public Property statusChangeDate As String
        Get
            Return _statusChangeDate
        End Get
        Set(value As String)
            _statusChangeDate = value
        End Set
    End Property

    Private _statusReasonCode As String
    ''' <summary> 
    '''In the case of a REJECTED or DISPUTED status, the reason code received in a return
    ''' </summary> 
    ''' <returns></returns> 
    Public Property statusReasonCode As String
        Get
            Return _statusReasonCode
        End Get
        Set(value As String)
            _statusReasonCode = value
        End Set
    End Property

    Private _statusReason As String
    ''' <summary> 
    '''In the case of a REJECTED or DISPUTED status, the text description for why the mandate was returned (e.g. bank account closed)
    ''' </summary> 
    ''' <returns></returns> 
    Public Property statusReason As String
        Get
            Return _statusReason
        End Get
        Set(value As String)
            _statusReason = value
        End Set
    End Property

#Region "IDisposable Support"
    Private disposedValue As Boolean ' To detect redundant calls

    ' IDisposable
    Protected Overridable Sub Dispose(disposing As Boolean)
        If Not disposedValue Then
            If disposing Then
                ' TODO: dispose managed state (managed objects).
            End If

            ' TODO: free unmanaged resources (unmanaged objects) and override Finalize() below.
            ' TODO: set large fields to null.
        End If
        disposedValue = True
    End Sub

    ' TODO: override Finalize() only if Dispose(disposing As Boolean) above has code to free unmanaged resources.
    'Protected Overrides Sub Finalize()
    '    ' Do not change this code.  Put cleanup code in Dispose(disposing As Boolean) above.
    '    Dispose(False)
    '    MyBase.Finalize()
    'End Sub

    ' This code added by Visual Basic to correctly implement the disposable pattern.
    Public Sub Dispose() Implements IDisposable.Dispose
        ' Do not change this code.  Put cleanup code in Dispose(disposing As Boolean) above.
        Dispose(True)
        ' TODO: uncomment the following line if Finalize() is overridden above.
        ' GC.SuppressFinalize(Me)
    End Sub
#End Region

End Class
